name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Project_Path: CS2Cheat.csproj 
      Output_Dir: publish

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build and publish project
      run: dotnet publish $env:Project_Path -c Release -o $env:Output_Dir -r win-x64 /p:PublishSingleFile=true 
          /p:IncludeNativeLibrariesForSelfExtract=true 
          /p:IncludeAllContentForSelfExtract=true 
          /p:DeleteExistingFiles=true 
          --self-contained false 
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    - name: Upload only .exe file
      uses: actions/upload-artifact@v4
      with:
        name: Built-Executable
        path: ${{ env.Output_Dir }}/*.exe
