name: Build and Release Single EXE

on:
  push:
    tags:
      - 'v1.7.6 autobuild'  

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Single EXE
      run: |
        dotnet publish CS2Cheat.csproj `
          -c Release `
          -r win-x64 `
          --framework net8.0-windows `
          /p:PublishSingleFile=true `
          /p:IncludeNativeLibrariesForSelfExtract=true `
          /p:IncludeAllContentForSelfExtract=true `
          /p:DeleteExistingFiles=true `
          --self-contained false `
          -o publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CS2Cheat-exe
        path: publish/*.exe

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: publish/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
